development:
  bucket_name: test-zips.greenasjade.net
  access_key_id: AKIAI3Y5C5VCJ2TEKVVQ
  secret_access_key: Kf9fRWCc636vWTVGEUSXMpbeKotdMldW8hwyGD1Ca
  max_file_size: 10485760
       
test:
  bucket_name: test_bucket
  access_key_id: 
  secret_access_key: 
  max_file_size: 1048576
  
production:
  bucket_name: test-zips.greenasjade.net
  access_key_id: AKIAI3Y5C5VCJ2TEKVVQ
  secret_access_key: Kf9fRWCc636vWTVGEUSXMpbeKotdMldW8hwyGD1Ca
  max_file_size: 10485760

